wagtail/gsoc

2023/README.md
2023/suyash-srivastava/README.md

Hey this PR is one of the steps of the checklist, from the contributor guidelines.
Additional Context:
Looking forward to keep up my contributions in wagtail, but sad to hear that you removed Stimulus Project and Black mode for admin projects, as I have made a significant amount of efforts and research in the field.
Still No Worries.
Thank you.

Added folder with my name and appended my name in the file.

---

2023/README.md
2023/elton-omwega/README.md

This pull request add my name to the contributors list and creates a folder with my name as well as a READMe file for the same.
I have also checked all the tasks completed at this point in time.

Add Elton Omwega to Contributors list

---

2023/README.md

add_manish_dhakal

---

.idea/.gitignore
.idea/gsoc.iml
.idea/inspectionProfiles/Project_Default.xml
.idea/inspectionProfiles/profiles_settings.xml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
2023/Manish Dhakal/README.md

completed all the tasks as instructed in [contributor-guide.md](https://github.com/wagtail/gsoc/blob/main/contributor-guide.md)

create my folder and add readme.md

---

2023/README.md

Add Amey Shinde

---

2023/Krishna-Dhakad/Readme.md

updated the readme file added intro skills and projects

Krishna dhakad intro

---

2023/README.md

Updated Readme.md

---

2023/README.md
2023/vallabhtiwari/README.md

Sorry for so late after the introductions. Had some personal problems. Will add further checks after completing tasks.

Tasks from the contributor-guide

---

2023/README.md
2023/amey-shinde/README.md

This is an update for creating a Markdown table and adding further sections like Checklists and Research with issues that I would like to work on.

Markdown table

---

contributor-guide.md

This should be advice not advise

Fix typo in contributor Readme

---

2023/README.md
2023/sobhan-bera/README.md

1. Added name in the default README.md file
2. Added introduction section in personal README file
3. Also added Tasks that I completed along with Research section.
4. Also added an image to show that I have performed the tutorial.

Added: Self Introductory README

---

2023/Abinash Satapathy/README.md
2023/README.md
contributor-guide.md
project-ideas.md

- Added my name to the list of participants
- Completed the checklists which I could complete until now.
- More updates about writing blog and Django/Wagtail will be completed soon! 😄

Docs: Complete `checklists` for `GSoC`

---

2023/README.md
2023/Sudarsan/README.md

- Sticking to the advice given in the contributor-guide.md to get well versed in wagtail's community.

Introduction and tasks checklist updated 

---

2023/README.md
2023/vibhakar-solanki/README.md

Adding myself to the 2023 gsoc participants :smile:

feat: add Vibhakar solanki to `2023/README.md` and Personal Readme

---

2023/README.md

Added my name following the sorting order.

Added My Name to Participant's Lists

---

2023/Piyush Srivastava/readme.md

Created a folder with my name and added a readme.md file with my Introduction and Contributions along with the social Links.

Added A folder with My Name.

---

2023/Mayank_Pandey/README.md

Added my Introduction from GitHub discussions and checklists mentioned in the GSOC contributor-guide.

data: Mayank Pandey (Introduction for GSOC)

---

2023/Ahmed-Hanoon/README.md

updating contributer info

---

2023/Ezad Zamily/README.md
2023/README.md

Adding folder Ezad Zamily into the 2023 folder with my README

Adding Ezad Zamily 

---

2023/Ahmed-Hanoon/README.md

tried my best to keep it hemingway <6, so the blog had to be too short

Blog+website added

---

2023/Mehul_Aggarwal/README.md

Added Research and the Resources GSOC project(Had to made a separate PR due to some git issue with the previous one)

Added Research
